services:
- type: web
  name: my-rails-app
  env: docker
  dockerfilePath: ./Dockerfile
  buildCommand: docker build -t my-rails-app .
  startCommand: bundle exec rails server -p 3000 -b 0.0.0.0
  envVars:
  - key: RAILS_ENV
    value: production
  - key: DATABASE_URL
    fromDatabase:
      name: my-mysql-db
      property: connectionString
  - key: RAILS_MAX_THREADS
    value: "5"
  - key: AWS_ACCESS_KEY_ID
    sync: true
    name: AWS_ACCESS_KEY_ID
  - key: AWS_SECRET_ACCESS_KEY
    sync: true
    name: AWS_SECRET_ACCESS_KEY

databases:
- name: my-mysql-db
  type: mysql
