services:
- type: web
  name: Pigeon
  env: docker
  dockerfilePath: ./Dockerfile
  buildCommand: docker build -t pigeon .
  startCommand: bundle exec rails server -p 3000 -b 0.0.0.0
  envVars:
  - key: RAILS_ENV
    value: production
  - key: DATABASE_URL
    fromDatabase:
      name: pigeon_production
      property: connectionString
  - key: RAILS_MAX_THREADS
    value: "5"
  - key: AWS_ACCESS_KEY_ID
    sync: true
    name: AWS_ACCESS_KEY_ID
  - key: AWS_SECRET_ACCESS_KEY
    sync: true
    name: AWS_SECRET_ACCESS_KEY

databases:
- name: pigeon_production
  type: mysql
